services:
  app:
    container_name: inventory-app
    build: .
    ports:
      - "1234:1234"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - postgres_server
    networks:
      - inventory-app-network
      - adminer-network
  
  postgres_server:
    container_name: postgres_server
    # image: postgres:17.1 
    build: ./scripts/
    healthcheck:
      test: ["CMD", "bash", "-c", "./dbIsEmpty.sh"]
      start_period: 10s
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: odin
      POSTGRES_PASSWORD: secreto
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adminer-network
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - adminer-network

volumes:
  postgres-data:

networks:
  adminer-network:
    name: db_adminer-network
  inventory-app-network:
 

 
