# 1. For build React app
# syntax=docker/dockerfile:1.4
ARG NODE_VERSION=20.13.1

FROM node:${NODE_VERSION}-alpine AS development

WORKDIR /app

COPY package.json .
COPY package-lock.json .

# RUN npm install

# Use npm ci when you have not already run npm install
RUN npm ci

COPY . . 
# TODO: VER LUEGO
# COPY .nginx .

ENV CI=true
ENV PORT=5173

# CMD [ "npm", "start" ]
CMD ["sh", "-c", "npm run dev"]



FROM development as build

RUN npm run build
 
 
# # install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /

# # CMD [ "npm", "start" ]
# CMD ["sh", "-c", "npm run dev"]

    # # 2. For Nginx setup
FROM nginx:stable
 
    
WORKDIR /usr/share/nginx/html
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
